2017-08-16 19:50:35,683 spiders.py[line:68] INFO Reading start URLs from redis key 'autohome:start_urls' (batch size: 1, encoding: utf-8
2017-08-16 19:50:39,085 spiders.py[line:95] DEBUG Read 1 requests from 'autohome:start_urls'
2017-08-16 19:50:40,101 spider_autohome.py[line:58] INFO url is: http://www.autohome.com.cn/795/.
2017-08-16 19:50:40,785 spiders.py[line:95] DEBUG Read 1 requests from 'autohome:start_urls'
2017-08-16 19:50:49,440 spider_autohome.py[line:58] INFO url is: http://www.autohome.com.cn/204/.
2017-08-16 19:50:49,470 spiders.py[line:95] DEBUG Read 1 requests from 'autohome:start_urls'
2017-08-16 19:50:53,933 spider_autohome.py[line:58] INFO url is: http://www.autohome.com.cn/4298/.
2017-08-16 19:50:53,963 spider_autohome.py[line:69] ERROR failed, url is:(http://www.autohome.com.cn/4298/), error info is:(Traceback (most recent call last):
  File "C:\Users\timothy\Desktop\autohome\autohome\car\spiders\spider_autohome.py", line 65, in parse
    request = Request(url, callback=self.parse2)
  File "E:\python27\lib\site-packages\scrapy\http\request\__init__.py", line 25, in __init__
    self._set_url(url)
  File "E:\python27\lib\site-packages\scrapy\http\request\__init__.py", line 58, in _set_url
    raise ValueError('Missing scheme in request url: %s' % self._url)
ValueError: Missing scheme in request url: k.autohome.com.cn/4298/9447/#pvareaid=101484
)
2017-08-16 19:50:53,980 spiders.py[line:95] DEBUG Read 1 requests from 'autohome:start_urls'
